Implement Test Timing Functionality
jakejack13/SPEED pull request #51
Opened 2024-02-13 23:32 UTC by owenxr

2024-02-14 00:37 UTC, jakejack13 requested changes
Documentation and style cleanup

2024-02-14 00:37 UTC, jakejack13 commented on leaders/src/main/java/edu/cornell/KafkaConsumerRunner.java
> +import lombok.*;
Import explicitly instead of using `.*`

2024-02-14 00:37 UTC, jakejack13 commented on leaders/src/main/java/edu/cornell/TestResultsRecord.java
> +import java.util.Map;
Remove unused imports

2024-02-14 00:37 UTC, jakejack13 commented on leaders/src/main/java/edu/cornell/TestResultsRecord.java
> +public class TestResultsRecord {
Can converted to a record

```suggestion
public record TestResultsRecord {
```

2024-02-14 00:37 UTC, jakejack13 commented on leaders/src/main/java/edu/cornell/TestResultsRecord.java
> +    private Integer elapsedTime;
Need class and field specifications

2024-02-14 00:37 UTC, jakejack13 commented on leaders/src/main/java/edu/cornell/TestResultsRecordDeserializer.java
> +public class TestResultsRecordDeserializer implements Deserializer<TestResultsRecord> {
Need class specification

2024-02-14 00:37 UTC, jakejack13 commented on workers/src/main/java/edu/cornell/testenv/testrunner/OutputTestExecutionListener.java
> +    private long timeTaken = 0;
Need field specification

2024-02-14 00:37 UTC, jakejack13 commented on workers/src/main/java/edu/cornell/testoutputstream/KafkaTestOutputStream.java
> +import lombok.Data;
Remove unused imports

2024-02-14 00:37 UTC, jakejack13 commented on workers/src/main/java/edu/cornell/testoutputstream/TestResultsRecord.java
> +public class TestResultsRecord {
Can be changed to a record

```suggestion
public record TestResultsRecord {
```

2024-02-14 00:37 UTC, jakejack13 commented on workers/src/main/java/edu/cornell/testoutputstream/TestResultsRecord.java
> +    private Integer elapsedTime;
Need class and field specifications

2024-02-14 00:37 UTC, jakejack13 commented on workers/src/main/java/edu/cornell/testoutputstream/TestResultsRecordSerializer.java
> +public class TestResultsRecordSerializer implements Serializer<TestResultsRecord> {
Need class specification

2024-02-14 00:39 UTC, jakejack13 requested changes
More style

2024-02-14 00:39 UTC, jakejack13 commented on leaders/src/main/java/edu/cornell/KafkaConsumerRunner.java
> +
Why you do this

```suggestion
```

2024-02-19 20:26 UTC, MitchellGray100 submitted a review, later dismissed
LGTM

2024-02-19 20:38 UTC, jakejack13 approved these changes
LGTM

2024-02-19 20:39 UTC, merged