SPEED-1: Add build system component
jakejack13/SPEED pull request #7
Opened 2023-12-04 19:48 UTC by MitchellGray100

### Description

This PR adds the repository building mechanism for inputs to the worker

2023-12-08 19:20 UTC, jakejack13 requested changes
Looks good overall but needs more documentation

2023-12-08 19:20 UTC, jakejack13 commented on workers/src/main/java/edu/cornell/repository/ConfigParser.java
> +    private EnumMap<Category, List<String>> configMap = new EnumMap<>(Category.class);
I would add some documentation to these fields (just for posterity sake)

2023-12-08 19:20 UTC, jakejack13 commented on workers/src/main/java/edu/cornell/repository/ConfigParser.java
> +    public static class ConfigSyntaxException extends Exception {
I've been putting exceptions in their own files. Should we instead move them as static classes? Doesn't make a difference except in style

2023-12-08 19:20 UTC, jakejack13 commented on workers/src/main/java/edu/cornell/repository/ConfigParser.java
> +public class ConfigParser {
In the class comment, can you add documentation on what the syntax of the config file is? I'm struggling to understand how this one is laid out and parsed. Can you maybe add an example config file into this package as well for reference?

2023-12-08 19:20 UTC, jakejack13 commented on workers/src/main/java/edu/cornell/repository/ConfigParser.java
> +    public enum Category {
Add documentation to this enum

2023-12-09 17:05 UTC, jakejack13 requested changes
A couple more documentation things

2023-12-09 17:05 UTC, jakejack13 commented on workers/src/main/java/edu/cornell/repository/ConfigSyntaxException.java
> +public class ConfigSyntaxException extends Exception {
Documentation needed explaining what this exception is

2023-12-09 17:05 UTC, jakejack13 commented on workers/src/main/java/edu/cornell/repository/RepositoryBuildException.java
> +@Data
I'm dumb so please remove these two annotations

2023-12-09 17:05 UTC, jakejack13 commented on workers/src/main/java/edu/cornell/repository/Config.java
> +    public Config(String configFilePath) throws ConfigSyntaxException, IOException {
Documentation needed on the field and the constructor

2023-12-09 20:39 UTC, owenxr approved these changes
LGTM

2023-12-10 05:19 UTC, jakejack13 requested changes
Please remove the `workers/.idea` directory and add in the missing documentation that are from the remaining comments

2023-12-10 05:19 UTC, jakejack13 commented on workers/.idea/.gitignore
Remove this file

2023-12-10 05:19 UTC, jakejack13 commented on workers/.idea/gradle.xml
Remove this file

2023-12-10 05:19 UTC, jakejack13 commented on workers/.idea/inspectionProfiles/Project_Default.xml
Remove this file

2023-12-10 05:19 UTC, jakejack13 commented on workers/.idea/misc.xml
Remove this file

2023-12-10 05:19 UTC, jakejack13 commented on workers/.idea/uiDesigner.xml
Remove this file

2023-12-10 05:19 UTC, jakejack13 commented on workers/.idea/vcs.xml
Remove this file

2023-12-10 06:09 UTC, jakejack13 requested changes
Documentation good, just need those `workers/.idea` files deleted

2023-12-10 06:38 UTC, jakejack13 approved these changes
LGTM

2023-12-10 18:49 UTC, merged